project:
  type: website

website:
  title: "Blogtest"
  site-url: "https://rgieseke.github.io/blogtest/"
  search: false
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
    html-math-method: katex
execute:
  freeze: auto


